Solucao/config/routes.rb
Rails.application.routes.draw do

  #use_doorkeeper

  #API routes
  namespace :api, except:[:new, :edit] do
    namespace :v1 do
          post 'users/auth/sign_in', to: 'users#sign_in'
          resources :enterprises
    end
  end

  #Application Routes
  root 'sessions#new'

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create]

  delete '/logout', to: 'sessions#destroy', as: :logout

  resources :enterprises
  resources :enterprise_types

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Solucao/app/controllers/enterprise_types_controller.rb
class EnterpriseTypesController < ApplicationController
  before_action :set_enterprise_type, only: [:show, :edit, :update, :destroy]

  # GET /enterprise_types
  # GET /enterprise_types.json
  def index
    @enterprise_types = EnterpriseType.all
  end

  # GET /enterprise_types/1
  # GET /enterprise_types/1.json
  def show
  end

  # GET /enterprise_types/new
  def new
    @enterprise_type = EnterpriseType.new
  end

  # GET /enterprise_types/1/edit
  def edit
  end

  # POST /enterprise_types
  # POST /enterprise_types.json
  def create
    @enterprise_type = EnterpriseType.new(enterprise_type_params)

    respond_to do |format|
      if @enterprise_type.save
        format.html { redirect_to @enterprise_type, notice: 'Enterprise type was successfully created.' }
        format.json { render :show, status: :created, location: @enterprise_type }
      else
        format.html { render :new }
        format.json { render json: @enterprise_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enterprise_types/1
  # PATCH/PUT /enterprise_types/1.json
  def update
    respond_to do |format|
      if @enterprise_type.update(enterprise_type_params)
        format.html { redirect_to @enterprise_type, notice: 'Enterprise type was successfully updated.' }
        format.json { render :show, status: :ok, location: @enterprise_type }
      else
        format.html { render :edit }
        format.json { render json: @enterprise_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enterprise_types/1
  # DELETE /enterprise_types/1.json
  def destroy
    @enterprise_type.destroy
    respond_to do |format|
      format.html { redirect_to enterprise_types_url, notice: 'Enterprise type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enterprise_type
      @enterprise_type = EnterpriseType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enterprise_type_params
      params.require(:enterprise_type).permit(:enterprise_type_code, :name)
    end
end

Solucao/app/helpers/enterprise_types_helper.rb
module EnterpriseTypesHelper
end

Solucao/app/views/enterprise_types/_form.html.erb
<%= form_with(model: enterprise_type, local: true) do |form| %>
  <% if enterprise_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enterprise_type.errors.count, "error") %> prohibited this enterprise_type from being saved:</h2>

      <ul>
      <% enterprise_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :enterprise_type_code %>
    <%= form.number_field :enterprise_type_code, id: :enterprise_type_enterprise_type_code %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :enterprise_type_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Solucao/app/views/enterprise_types/edit.html.erb
<h1>Editing Enterprise Type</h1>

<%= render 'form', enterprise_type: @enterprise_type %>

<%= link_to 'Show', @enterprise_type %> |
<%= link_to 'Back', enterprise_types_path %>

Solucao/app/views/enterprise_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enterprise Types</h1>

<table>
  <thead>
    <tr>
      <th>Enterprise type code</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enterprise_types.each do |enterprise_type| %>
      <tr>
        <td><%= enterprise_type.enterprise_type_code %></td>
        <td><%= enterprise_type.name %></td>
        <td><%= link_to 'Show', enterprise_type %></td>
        <td><%= link_to 'Edit', edit_enterprise_type_path(enterprise_type) %></td>
        <td><%= link_to 'Destroy', enterprise_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enterprise Type', new_enterprise_type_path %>

Solucao/app/views/enterprise_types/new.html.erb
<h1>New Enterprise Type</h1>

<%= render 'form', enterprise_type: @enterprise_type %>

<%= link_to 'Back', enterprise_types_path %>

Solucao/app/views/enterprise_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Enterprise type code:</strong>
  <%= @enterprise_type.enterprise_type_code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @enterprise_type.name %>
</p>

<%= link_to 'Edit', edit_enterprise_type_path(@enterprise_type) %> |
<%= link_to 'Back', enterprise_types_path %>