Solucao/config/routes.rb
Rails.application.routes.draw do

  #use_doorkeeper

  #API routes
  namespace :api, except:[:new, :edit] do
    namespace :v1 do
          post 'users/auth/sign_in', to: 'users#sign_in'
          resources :enterprises
    end
  end

  #Application Routes
  root 'sessions#new'

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create]

  delete '/logout', to: 'sessions#destroy', as: :logout

  resources :enterprises
  resources :enterprise_types

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Solucao/app/controllers/api/v1/enterprises_controller.rb
module Api
  module V1
    class EnterprisesController < BaseController
      before_action :authorize

      def index
        json_response Enterprise.filter(params.slice(:enterprise_types, :name))
      end

      def show
        json_response Enterprise.find(params[:id])
      end

      def create
        json_response Enterprise.create(params[:empresa]), :created
      end

      def update
        json_response Enterprise.update(params[:id], params[:empresa])
      end

      def destroy
        json_response Enterprise.destroy(params[:id])
      end
    end
  end
end

Solucao/app/controllers/enterprises_controller.rb
class EnterprisesController < ApplicationController
  before_action :set_enterprise, only: [:show, :edit, :update, :destroy]

  # GET /enterprises
  # GET /enterprises.json
  def index
    @enterprises = Enterprise.all
  end

  # GET /enterprises/1
  # GET /enterprises/1.json
  def show
  end

  # GET /enterprises/new
  def new
    @enterprise = Enterprise.new
  end

  # GET /enterprises/1/edit
  def edit
  end

  # POST /enterprises
  # POST /enterprises.json
  def create
    @enterprise = Enterprise.new(enterprise_params)

    respond_to do |format|
      if @enterprise.save
        format.html { redirect_to @enterprise, notice: 'Enterprise was successfully created.' }
        format.json { render :show, status: :created, location: @enterprise }
      else
        format.html { render :new }
        format.json { render json: @enterprise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enterprises/1
  # PATCH/PUT /enterprises/1.json
  def update
    respond_to do |format|
      if @enterprise.update(enterprise_params)
        format.html { redirect_to @enterprise, notice: 'Enterprise was successfully updated.' }
        format.json { render :show, status: :ok, location: @enterprise }
      else
        format.html { render :edit }
        format.json { render json: @enterprise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enterprises/1
  # DELETE /enterprises/1.json
  def destroy
    @enterprise.destroy
    respond_to do |format|
      format.html { redirect_to enterprises_url, notice: 'Enterprise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enterprise
      @enterprise = Enterprise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enterprise_params
      params.require(:enterprise).permit(:name, :enterprise_type_id)
    end
end

Solucao/app/helpers/enterprises_helper.rb
module EnterprisesHelper
end

Solucao/app/views/enterprises/_form.html.erb
<%= form_with(model: enterprise, local: true) do |form| %>
  <% if enterprise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enterprise.errors.count, "error") %> prohibited this enterprise from being saved:</h2>

      <ul>
      <% enterprise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :enterprise_name %>
  </div>

  <div class="field">
    <%= form.label :enterprise_type_id %>
    <%= form.select :enterprise_type_id, EnterpriseType.all.collect {|p| [ p.name, p.enterprise_type_code ] }, {include_blank: 'Undefined'}%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Solucao/app/views/enterprises/edit.html.erb
<h1>Editing Enterprise</h1>

<%= render 'form', enterprise: @enterprise %>

<%= link_to 'Show', @enterprise %> |
<%= link_to 'Back', enterprises_path %>

Solucao/app/views/enterprises/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enterprises</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Enterprise type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enterprises.each do |enterprise| %>
      <tr>
        <td><%= enterprise.name %></td>
        <td><%= enterprise.enterprise_type_id %></td>
        <td><%= link_to 'Show', enterprise %></td>
        <td><%= link_to 'Edit', edit_enterprise_path(enterprise) %></td>
        <td><%= link_to 'Destroy', enterprise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enterprise', new_enterprise_path %>

Solucao/app/views/enterprises/new.html.erb
<h1>New Enterprise</h1>

<%= render 'form', enterprise: @enterprise %>

<%= link_to 'Back', enterprises_path %>

Solucao/app/views/enterprises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @enterprise.name %>
</p>

<p>
  <strong>Enterprise type:</strong>
  <%= @enterprise.enterprise_type_id %>
</p>

<%= link_to 'Edit', edit_enterprise_path(@enterprise) %> |
<%= link_to 'Back', enterprises_path %>